from fastapi import APIRouter
from app.models.repository import get_recent_early_warnings

router = APIRouter()

@router.get("/predictions")
def get_predictions():
    """
    Returns the most recent early warnings generated by the prediction poller.
    """
    warnings = get_recent_early_warnings(limit=20)
    return {"status": "success", "predictions": warnings}
